<a href="https://colab.research.google.com/github/cdsouza2701/cdsouza2701/blob/main/PP_(1_3)_Historical_Revenue_Analysis_Using_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Task: Calculate Total Revenue for a company with changing pricing.

In [1]:
import pandas as pd

## Basic Exploration

In [2]:
# Load data
transactions = pd.read_csv('transactions.csv')
price_history = pd.read_csv('price_history.csv')
products = pd.read_csv('products.csv')

In [ ]:
transactions.head()

   order_detail_id  order_id  order_date  pizza_id  quantity
0                1         1  2026-01-01         4         1
1                2         2  2026-01-01         6         1
2                3         2  2026-01-01         2         1
3                4         2  2026-01-01         9         1
4                5         2  2026-01-01        10         1

In [ ]:
price_history.head()

   pizza_id effective_date  price
0         1     2026-01-01  20.75
1         2     2026-01-01  17.95
2         3     2026-01-01  20.75
3         4     2026-01-01  16.50
4         5     2026-01-01  20.25

In [ ]:
products.head()

   pizza_id             name  current_price
0         1      BBQ Chicken          20.75
1         2           Cheese          18.50
2         3  Chicken Alfredo          20.75
3         4         Hawaiian          20.50
4         5       Margherita          20.75

IMPORTANT

You do NOT need to memorize all this immediately.

Over time, these become your standard “first exploration steps.”

Most analysts do some version of:

- head()
- shape
- columns
- dtypes
- isnull()
- duplicated()
- nunique()

every single time they get a new dataset.

That becomes your investigation toolkit.

In [ ]:
transactions.dtypes

order_detail_id     int64
order_id            int64
order_date         object
pizza_id            int64
quantity            int64
dtype: object

In [ ]:
transactions.isnull().sum()

order_detail_id    0
order_id           0
order_date         0
pizza_id           0
quantity           0
dtype: int64

In [ ]:
transactions.duplicated().sum()

np.int64(0)

In [ ]:
transactions.nunique() #nunique

order_detail_id    7164
order_id           3530
order_date           59
pizza_id             10
quantity              6
dtype: int64

#Part 2: Working on solution

In [3]:
#Load data
transactions = (pd.read_csv('transactions.csv', parse_dates=["order_date"])). sort_values(by="order_date")

price_history = (pd.read_csv('price_history.csv', parse_dates=['effective_date'])).sort_values(by='effective_date')

In [3]:
transactions.head()

    order_detail_id  order_id order_date  pizza_id  quantity
0                 1         1 2026-01-01         4         1
93               94        43 2026-01-01         8         1
94               95        44 2026-01-01         5         1
95               96        45 2026-01-01         2         1
96               97        45 2026-01-01         4         1

In [4]:
price_history.head()

   pizza_id effective_date  price
0         1     2026-01-01  20.75
1         2     2026-01-01  17.95
2         3     2026-01-01  20.75
3         4     2026-01-01  16.50
4         5     2026-01-01  20.25

In [5]:
transactions.shape

(7164, 5)

In [7]:
price_history.shape

(22, 3)

In [8]:
transactions.dtypes

order_detail_id             int64
order_id                    int64
order_date         datetime64[ns]
pizza_id                    int64
quantity                    int64
dtype: object

In [9]:
price_history.dtypes

pizza_id                   int64
effective_date    datetime64[ns]
price                    float64
dtype: object

In [19]:
transactions["order_detail_id"].duplicated().sum()
#transactions["order_detail_id"].is_unique

np.int64(0)

In [15]:
price_history.duplicated(
    subset=["pizza_id", "effective_date"]
).sum()

np.int64(0)

In [5]:
# revenue = pd.merge_asof(
#    transactions.sort_values("order_date"),
#    price_history.sort_values("effective_date"),
#     by="pizza_id",
#     left_on="order_date",
#     right_on="effective_date",

revenue = pd.merge_asof(
    transactions,
    price_history,
    by='pizza_id',
    left_on='order_date',
    right_on='effective_date',
    direction='backward'
).assign(line_total = lambda x: x.price * x.quantity).line_total.sum()

revenue

np.float64(161144.34999999998)